import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#373b3f',
        flex: 1,
        width: '100%',
        height: 844,
        overflow: 'hidden',
        borderRadius: 8,
    },
    profileImage: {
        alignSelf: 'center',
        top: 83,
        width: 100,
        height: 100,
        position: 'absolute',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#1CC29F',
    },
    expenseHistory: {
        top: 210,
        padding: 16,
        justifyContent: 'space-between',
        right: '6.41%',
        width: '87.69%',
        borderRadius: 8,
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        left: '5.9%',
        position: 'absolute',
    },
    name: {
        top: 285,
        borderRadius: 8,
        padding: 16,
        justifyContent: 'space-between',
        right: '6.41%',
        width: '87.69%',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        left: '5.9%',
        position: 'absolute',
    },
    arrow: {
        position: 'absolute',
        left: 30,
        top: 50,
    },
    logoutContainer: {
        position: 'absolute',
        right: 30,
        top: 50,
        alignItems: 'center',
    },
    logoutText: {
        color: 'white',
    },
    button: {
        width: '87.44%',
        top: 489,
        right: '6.67%',
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        left: '5.9%',
        position: 'absolute',
        borderRadius: 8,
    },
    buttonText: {
        fontSize: 16,
        color: '#d73018',
        fontWeight: 'bold',
    },
    textBold: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    infoText: {
        fontSize: 16,
        color: '#333',
    },
    changeEmail: {
        top: 360,
        borderTopRightRadius: 8,
        borderTopLeftRadius: 8,
        padding: 16,
        justifyContent: 'space-between',
        right: '6.41%',
        width: '87.69%',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        left: '5.9%',
        position: 'absolute',
    },
    changePassword: {
        top: 414,
        borderBottomLeftRadius: 8,
        borderBottomRightRadius: 8,
        padding: 16,
        justifyContent: 'space-between',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: '#fff',
        left: '5.9%',
        right: '6.41%',
        width: '87.69%',
        position: 'absolute',
    },
});

export default styles;
